#!/usr/bin/env python3
"""
Generate strongly-typed C# localization class from JSON locale files.

Reads shared/locales/en.json and shared/locales/zh.json, generates
a Loc.cs file with static properties for each translation key.

Usage:
    python scripts/generate_locales.py

Output:
    frontend/windows/Generated/Loc.cs
"""

import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
LOCALES_DIR = os.path.join(SCRIPT_DIR, "locales")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "frontend", "windows", "Generated", "Loc.cs")

# Languages to generate (order matters: first is fallback)
LANGUAGES = ["en", "zh"]


def load_locale(lang: str) -> dict:
    """Load a locale JSON file."""
    path = os.path.join(LOCALES_DIR, f"{lang}.json")
    if not os.path.exists(path):
        print(f"Warning: {path} not found, skipping", file=sys.stderr)
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def key_to_property_name(key: str) -> str:
    """Convert a dot-separated key to a PascalCase property name.

    Examples:
        nav.home -> Nav_Home
        settings.persist_desc -> Settings_PersistDesc
        error.fan_curve_min_points -> Error_FanCurveMinPoints
    """
    parts = key.split(".")
    result_parts = []
    for part in parts:
        # Convert snake_case to PascalCase
        words = part.split("_")
        pascal = "".join(w.capitalize() for w in words if w)
        result_parts.append(pascal)
    return "_".join(result_parts)


def escape_csharp_string(s: str) -> str:
    """Escape a string for use in a C# verbatim string literal (@\"...\")."""
    return s.replace('"', '""')


def generate_cs(locales: dict[str, dict]) -> str:
    """Generate the Loc.cs file content."""
    # Collect all keys from all languages
    all_keys: set[str] = set()
    for lang_data in locales.values():
        all_keys.update(lang_data.keys())

    # Sort keys for deterministic output
    sorted_keys = sorted(all_keys)

    lines = []
    lines.append("// <auto-generated>")
    lines.append("// This file was generated by scripts/generate_locales.py")
    lines.append("// DO NOT EDIT MANUALLY — edit shared/locales/*.json instead")
    lines.append("// </auto-generated>")
    lines.append("")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append("namespace XmaX;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Strongly-typed localization. Call SetLanguage() to switch.")
    lines.append("/// Falls back to English for missing keys.")
    lines.append("/// </summary>")
    lines.append("public static class Loc")
    lines.append("{")

    # Language data dictionaries
    for lang in LANGUAGES:
        data = locales.get(lang, {})
        lines.append(f"    private static readonly Dictionary<string, string> _{lang} = new()")
        lines.append("    {")
        for key in sorted_keys:
            value = data.get(key, "")
            escaped = escape_csharp_string(value)
            lines.append(f'        ["{key}"] = @"{escaped}",')
        lines.append("    };")
        lines.append("")

    # Current language field
    lines.append('    private static string _currentLang = "en";')
    lines.append("")

    # SetLanguage method
    lines.append("    /// <summary>Set the active language. Values: \"en\", \"zh\", or \"auto\".</summary>")
    lines.append("    public static void SetLanguage(string lang)")
    lines.append("    {")
    lines.append('        if (lang == "auto")')
    lines.append("        {")
    lines.append("            // Detect system language")
    lines.append("            var culture = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;")
    lines.append('            _currentLang = culture == "zh" ? "zh" : "en";')
    lines.append("        }")
    lines.append("        else")
    lines.append("        {")
    lines.append('            _currentLang = lang == "zh" ? "zh" : "en";')
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # Get method
    lines.append("    private static string Get(string key)")
    lines.append("    {")
    lines.append("        var dict = _currentLang switch")
    lines.append("        {")
    for lang in LANGUAGES:
        lines.append(f'            "{lang}" => _{lang},')
    lines.append("            _ => _en,")
    lines.append("        };")
    lines.append('        return dict.TryGetValue(key, out var val) ? val : _en.TryGetValue(key, out val) ? val : key;')
    lines.append("    }")
    lines.append("")

    # Format method
    lines.append("    /// <summary>Get a localized string with format arguments.</summary>")
    lines.append("    public static string F(string key, params object[] args)")
    lines.append("    {")
    lines.append("        return string.Format(System.Globalization.CultureInfo.CurrentCulture, Get(key), args);")
    lines.append("    }")
    lines.append("")

    # Static properties for each key
    for key in sorted_keys:
        prop_name = key_to_property_name(key)
        lines.append(f"    /// <summary>{escape_csharp_string(key)}</summary>")
        lines.append(f'    public static string {prop_name} => Get("{key}");')
        lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    # Load all locales
    locales = {}
    for lang in LANGUAGES:
        locales[lang] = load_locale(lang)

    # Generate C# file
    content = generate_cs(locales)

    # Write output
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    # Count keys
    total_keys = set()
    for lang_data in locales.values():
        total_keys.update(lang_data.keys())
    print(f"Generated {OUTPUT_FILE} with {len(total_keys)} keys")


if __name__ == "__main__":
    main()
